# -*- coding: utf-8 -*-
"""ImplementasiCaraKerjaK-MeansClustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTSCefvB8rgrwPabDnM0xLymO9qtAxSY
"""

from google.colab import drive
import pandas as pd
import matplotlib.pyplot as plt

"""READ DATASET"""

#Data Preprocessing
#letak path dataset kita

dfmhs=pd.read_csv('/content/drive/MyDrive/Matematika ITS/Serba Serbi Kuliah - Irvan Abdull Rahman/Semester 7/Kerja Praktik/nilaimahasiswa.csv', sep=';', engine = 'python')

dfmhs

dfmhs.describe()

dfmhs.info()

plt.scatter(dfmhs['uts'],dfmhs['uas'])

plt.xlabel("UTS")
plt.ylabel("UAS")
plt.title("Grafik Nilai Mahasiswa")

"""Membuat Data Training"""

x_train = dfmhs[['uts','uas']]

"""Feature Scaling"""

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)

x_train

"""CLUSTERING"""

from sklearn.cluster import KMeans
kmean = KMeans(n_clusters=2)
kmean

y_cluster = kmean.fit_predict(x_train)
y_cluster

dfmhs['Cluster'] = y_cluster
dfmhs

kmean.cluster_centers_

"""  VISUALISASI DATA HASIL CLUSTERING"""

plt.figure(figsize=(10,5))
plt.scatter(x_train[:,0],x_train[:,1],c=kmean.labels_)
plt.scatter(kmean.cluster_centers_[0,0],kmean.cluster_centers_[0,1],cmap='rainbow',marker='*',s=150,label='Centroid 0')
plt.scatter(kmean.cluster_centers_[1,0],kmean.cluster_centers_[1,1],cmap='rainbow',marker='*',s=150,label='Centroid 1')
#plt.scatter(kmean.cluster_centers_[2,0],kmean.cluster_centers_[2,1],cmap='rainbow',marker='*',s=150,label='Centroid 2')

plt.xlabel("UTS")
plt.ylabel("UAS")
plt.title("Grafik Nilai Mahasiswa")
plt.legend()

"""MENCARI K (JUMLAH KLASTER) TERBAIK"""

inertias = []
k_range = range(1,10)
for k in k_range:
  km = KMeans(n_clusters=k).fit(x_train)
  inertias.append(km.inertia_)

inertias

plt.xlabel("K")
plt.ylabel("Sum of error")
plt.plot(k_range,inertias)
plt.title("Elbow Method")
plt.grid()

dfmhs['Cluster'] = dfmhs['Cluster'].replace([0,1],['Kurang','Baik'])

dfmhs